services:
  proxy:
    container_name: nginx
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    networks:
      - dica_net
    depends_on:
      - postgres
      - api

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: dica
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - dica_net
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - dica_net
    restart: unless-stopped

  api:
    container_name: dica-api
    image: eduhass/dica-api:03
    depends_on:
      - postgres
    networks:
      - dica_net
    links: 
      - postgres

  # api:
  #   container_name: api_container
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   build: .
  #   image: dica-api:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - GIN_MODE=release
  #   links: 
  #     - postgres

networks:
  dica_net:
    driver: bridge

volumes:
  postgres:
  pgadmin: