definitions:
  answer.CreateAnswerRequest:
    properties:
      answer:
        type: string
    type: object
  answer.CreateAnswerResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.AnswerResponse'
      message:
        type: string
    type: object
  answer.DeleteAnswerResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.AnswerResponse'
      message:
        type: string
    type: object
  answer.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  answer.ListAnswersResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.AnswerResponse'
        type: array
      message:
        type: string
    type: object
  answer.ShowAnswerResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.AnswerResponse'
      message:
        type: string
    type: object
  answer.UpdateAnswerRequest:
    properties:
      answer:
        type: string
    type: object
  answer.UpdateAnswerResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.AnswerResponse'
      message:
        type: string
    type: object
  question.CreateQuestionRequest:
    properties:
      idquestion:
        type: integer
      optiona:
        type: string
      optionc:
        type: string
      optiond:
        type: string
      optioni:
        type: string
      question:
        type: string
    type: object
  question.CreateQuestionResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.QuestionResponse'
      message:
        type: string
    type: object
  question.DeleteQuestionResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.QuestionResponse'
      message:
        type: string
    type: object
  question.ErrorResponse:
    properties:
      errorCode:
        type: string
      message:
        type: string
    type: object
  question.ListQuestionsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.QuestionResponse'
        type: array
      message:
        type: string
    type: object
  question.ShowQuestionResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.QuestionResponse'
      message:
        type: string
    type: object
  question.UpdateQuestionRequest:
    properties:
      idquestion:
        type: integer
      optiona:
        type: string
      optionc:
        type: string
      optiond:
        type: string
      optioni:
        type: string
      question:
        type: string
    type: object
  question.UpdateQuestionResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.QuestionResponse'
      message:
        type: string
    type: object
  schemas.AnswerResponse:
    properties:
      answer:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
    type: object
  schemas.QuestionResponse:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      idquestion:
        type: integer
      optiona:
        type: string
      optionc:
        type: string
      optiond:
        type: string
      optioni:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /answer:
    delete:
      consumes:
      - application/json
      description: Delete a job answer
      parameters:
      - description: Answer identification
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/answer.DeleteAnswerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
      summary: Delete answer
      tags:
      - Answers
    get:
      consumes:
      - application/json
      description: Show a job answer
      parameters:
      - description: Answer identification
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/answer.ShowAnswerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
      summary: Show answer
      tags:
      - Answers
    post:
      consumes:
      - application/json
      description: Create a new job answer
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/answer.CreateAnswerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/answer.CreateAnswerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
      summary: Create answer
      tags:
      - Answers
    put:
      consumes:
      - application/json
      description: Update a job answer
      parameters:
      - description: Answer Identification
        in: query
        name: id
        required: true
        type: string
      - description: Answer data to Update
        in: body
        name: answer
        required: true
        schema:
          $ref: '#/definitions/answer.UpdateAnswerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/answer.UpdateAnswerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
      summary: Update answer
      tags:
      - Answers
  /answers:
    get:
      consumes:
      - application/json
      description: List all job answers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/answer.ListAnswersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/answer.ErrorResponse'
      summary: List answers
      tags:
      - Answers
  /question:
    delete:
      consumes:
      - application/json
      description: Delete a job question
      parameters:
      - description: Question identification
        in: query
        name: idquestion
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/question.DeleteQuestionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/question.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/question.ErrorResponse'
      summary: Delete question
      tags:
      - Questions
    get:
      consumes:
      - application/json
      description: Show a job question
      parameters:
      - description: Question identification
        in: query
        name: idquestion
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/question.ShowQuestionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/question.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/question.ErrorResponse'
      summary: Show question
      tags:
      - Questions
    post:
      consumes:
      - application/json
      description: Create a new job question
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/question.CreateQuestionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/question.CreateQuestionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/question.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/question.ErrorResponse'
      summary: Create question
      tags:
      - Questions
    put:
      consumes:
      - application/json
      description: Update a job question
      parameters:
      - description: Question Identification
        in: query
        name: idquestion
        required: true
        type: string
      - description: Question data to Update
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/question.UpdateQuestionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/question.UpdateQuestionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/question.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/question.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/question.ErrorResponse'
      summary: Update question
      tags:
      - Questions
  /questions:
    get:
      consumes:
      - application/json
      description: List all job questions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/question.ListQuestionsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/question.ErrorResponse'
      summary: List questions
      tags:
      - Questions
swagger: "2.0"
